{
 "title": "Red Hat OpenShift Streams for Apache Kafka",
 "tags": [
  "Strimzi",
  "Kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "strimzi_cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "kafka_instance_connection_limit"
    }
   },
   {
    "name": "kafka_broker",
    "label": "Broker",
    "query": {
     "query": "kafka_instance_connection_limit{instance_name=\"$strimzi_cluster_name\"}"
    }
   },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": {
     "query": "kas_topic_partition_log_size_bytes{strimzi_io_cluster=~\"$strimzi_cluster_name\",broker_id=~\"$kafka_broker\"}"
    }
   },
   {
    "name": "kafka_partition",
    "label": "Partition",
    "query": {
     "query": "kas_topic_partition_log_size_bytes{strimzi_io_cluster=~\"$strimzi_cluster_name\",broker_id=~\"$kafka_broker\",topic_name=~\"$kafka_topic\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Incoming Byte Rate",
   "type": "stat",
   "description": "Total incoming byte rate",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytes_in_total{topic=~\"$kafka_topic\",topic!=\"\",statefulset_kubernetes_io_pod_name=~\"$strimzi_cluster_name-kafka-$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Outgoing Byte Rate",
   "type": "stat",
   "description": "Total outgoing byte rate",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytes_out_total{topic=~\"$kafka_topic\",topic!=\"\",statefulset_kubernetes_io_pod_name=~\"$strimzi_cluster_name-kafka-$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messages_in_total{topic=~\"$kafka_topic\",topic!=\"\",statefulset_kubernetes_io_pod_name=~\"$strimzi_cluster_name-kafka-$kafka_broker\"}[1m]))",
     "legendFormat": "Total Incoming Messages Rate"
    }
   ]
  },
  {
   "title": "Incoming Messages Rate",
   "type": "stat",
   "description": "Incoming messages rate",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messages_in_total{topic=~\"$kafka_topic\",topic!=\"\",statefulset_kubernetes_io_pod_name=~\"$strimzi_cluster_name-kafka-$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Total partitions offline",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offline_partitions_count{statefulset_kubernetes_io_pod_name=~\"$strimzi_cluster_name-kafka-$kafka_broker\"})"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "graph",
   "description": "Byte rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytes_in_total{topic=~\"$kafka_topic\",topic!=\"\",statefulset_kubernetes_io_pod_name=~\"$strimzi_cluster_name-kafka-$kafka_broker\"}[1m]))",
     "legendFormat": "Total Incoming Byte Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytes_out_total{topic=~\"$kafka_topic\",topic!=\"\",statefulset_kubernetes_io_pod_name=~\"$strimzi_cluster_name-kafka-$kafka_broker\"}[1m]))",
     "legendFormat": "Total Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "graph",
   "description": "Kafka broker available space per disk.\n\nLegend label format: data-<disk>-<cluster name>-kafka-<broker ID>",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data(-[0-9]+)?-$strimzi_cluster_name-kafka-$kafka_broker\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Global Partition Count",
   "type": "stat",
   "description": "Total partitions",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_global_partition_count{strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kas_topic_partition_log_size_bytes{strimzi_io_cluster=~\"$strimzi_cluster_name\",broker_id=~\"$kafka_broker\",topic_name=~\"$kafka_topic\",partition_id=~\"$kafka_partition\"}",
     "legendFormat": "broker {{broker_id}}, topic {{topic_name}}, partition {{partition_id}}"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "graph",
   "description": "Kafka broker pods disk usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"data(-[0-9]+)?-$strimzi_cluster_name-kafka-$kafka_broker\"}",
     "legendFormat": "Used: {{persistentvolumeclaim}}"
    },
    {
     "expr": "kafka_broker_quota_softlimitbytes{statefulset_kubernetes_io_pod_name=~\"$strimzi_cluster_name-kafka-$kafka_broker\"}",
     "legendFormat": "Limit: {{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  }
 ]
}